version: '3'
services:
  zookeeper:  
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:  
    image: wurstmeister/kafka:latest
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "log_topic:5:1"
    ports:
      - "9092:9092"
  postgres:  
    image: postgres:latest
    environment:
       POSTGRES_PASSWORD: postgres 
    ports:  
      - "5432:54:32"
    
